import "./globals.css"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>PHANTOM TYPE</title>
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="initial-scale=1.0, width=device-width"
          key="viewport"
        />
        <meta name="description" content="Japan photo gallery" />
        <meta property="og:site_name" content="PHANTOM TYPE" />
        <meta property="og:type" content="article" />
        <meta name="twitter:title" content="PHANTOM TYPE" />
        <meta name="twitter:description" content="a Japan photo gallery" />
        <meta name="twitter:card" content="photo" />
        <meta name="twitter:site" content="@yusuke_kokubo" />
      </head>
      <body className={`bg-black text-white font-body ${inter.className}`}>
        {children}
      </body>
    </html>
  )
}
